### ISSUE TITLE
[FEAT] Redux connection with like

### ISSUE THREAD

**Issue by sareum-k** [sareum-k/wanted-codestates-project-9#10]
### Description
디럭스와 좋아요 연결하기

### Todo
- [ ] 좋아요 action 생성
- [ ] 좋아요 reducer 생성
- [ ] 연결 후 좋아요 추가된 결과 저장
